name: CI - Test and SonarCloud Analysis

on:
  push

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for SonarCloud analysis

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Replace with your project's Node.js version

      - name: Install dependencies
        run: npm i
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Adjust coverage report paths
        run: |
          sed -i 's|SF:/github/workspace/|SF:|g' coverage/lcov.info

      - name: List coverage directory contents
        run: ls -la coverage

      - name: Show lcov.info
        run: head -n 20 coverage/lcov.info

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=swent-group21_strive
            -Dsonar.organization=swent-group21
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=app
            -Dsonar.tests=__tests__
            -Dsonar.exclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.test.js,**/node_modules/**,**/assets/**
            -Dsonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.test.js,**/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.verbose=true
